version: "3"

services:
  notebook:
    build:
      context: .
      dockerfile: notebook/Dockerfile
    container_name: notebook
    volumes:
      - ./scripts:/home/jovyan/work
      - ./uploads:/home/jovyan/work/uploads
    ports:
      - 8888:8888

  namenode:
    build:
      context: .
      dockerfile: namenode/Dockerfile
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./scripts:/scripts
      - ./uploads:/uploads
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop.env

  datanode:
    build:
      context: .
      dockerfile: datanode/Dockerfile
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - hadoop.env

  resourcemanager:
    build:
      context: .
      dockerfile: resourcemanager/Dockerfile
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - hadoop.env

  nodemanager1:
    build:
      context: .
      dockerfile: nodemanager/Dockerfile
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - hadoop.env

  hbase:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbase
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - hbase-standalone.env

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hbase_data:
  hbase_zookeeper_data:
  data_uploads:
